apiVersion: apps/v1
kind: Deployment
metadata:
  name: sygnify-api
  namespace: sygnify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sygnify-api
  template:
    metadata:
      labels:
        app: sygnify-api
    spec:
      containers:
        - name: api
          image: sygnify-api:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sygnify-api-hpa
  namespace: sygnify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sygnify-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 