apiVersion: v1
kind: Namespace
metadata:
  name: sygnify
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sygnify-quota
  namespace: sygnify
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sygnify-network-policy
  namespace: sygnify
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress 