# Dockerfile for Streamlit Dashboard
FROM python:3.10-slim
WORKDIR /app
COPY frontend/requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY frontend /app
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_apps/main_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"] 